"""ATO mission-briefing data, the counterland control tasking and the typed target-list fields.

Keys follow describe/resolve.py; every value is a describe/templates.py template. The schema parts come
from build/ato_briefs.py and build/order_typing.py.
"""
from openaix.describe import templates as d
from openaix.describe.tables.order_fields import (abort_criteria, agency_ref, objective, procedure_ref, report_refs,
                                                  success_criteria, task_area, tasking_kind)


SUBJECTS = {
    "CASBrief": "CAS brief", "FACABrief": "FAC(A) brief", "SCARBrief": "SCAR brief", "AttackBrief": "attack brief",
    "AirToAirBrief": "air-to-air brief", "RefuelingBrief": "refuelling brief", "AirborneControlBrief": "airborne control brief",
    "ReconnaissanceBrief": "reconnaissance brief", "ElectromagneticBrief": "electromagnetic brief", "TransportBrief": "transport brief",
    "AirdropBrief": "airdrop brief", "AirAssaultBrief": "air assault brief", "PersonnelRecoveryBrief": "personnel recovery brief",
    "TrainingBrief": "training brief", "CustomBrief": "custom brief", "AirMovementLine": "line of the air movement table",
    "CounterlandControl": "counterland control task", "Survivor": "survivor", "EngagementMeans": "engagement means",
}

REMARKS = "notes for the aircrews that are not in the other fields of this brief"
CHANNEL = "radio channel"


def role_rule(*roles, single=False):
    """A "shall" sentence for a point reference whose role validate.references checks."""
    names = " or ".join("`" + role + "`" for role in roles)
    subject = "The point" if single else "Each point"
    return d.enforced(subject + " shall have the role " + names, "validator:openaix.check.validate.references")


def brief_field(tasking):
    return d.statement("This field gives the data of the mission brief for this " + tasking,
                       "The brief refers to the records of the resource catalogue and does not copy them")


def contact(clause):
    return d.statement("This field gives the agency that " + clause + ", with its radio channels")


def contacts(clause):
    return d.list_of("agencies that " + clause + ", with their radio channels")


def fscm_list(subject):
    return d.references("fire support coordination measures and airspace coordination areas", "are applicable to the " + subject)


def cas_fields(context, subject):
    """The CAS data that the CAS brief and the FAC(A) brief share."""
    return {
        (context, "controllers"): contacts("control the CAS for this " + subject),
        (context, "contact_points"): d.references("contact points", "the aircraft fly to before the controller gives them a task", role_rule("control")),
        (context, "initial_points"): d.references("initial points", "start the attack runs of the " + subject, role_rule("initial")),
        (context, "holding"): d.references("orbits, points or zones", "the aircraft use to hold before they get a task"),
        (context, "holding_altitude"): d.altitude_block("the holding stack"),
        (context, "fire_support_measures"): fscm_list(subject),
        (context, "friendly_lines"): d.references("lines and boundaries", "show the positions of the friendly ground forces"),
        (context, "ground_scheme_summary"): d.text("plan of the friendly ground forces, in short form"),
        (context, "laser_codes"): d.list_of("laser codes for the controller and the aircraft in this " + subject),
        (context, "marks"): d.list_of("types of target mark", "the controller can supply",
                                      "JP 3-09.3 (2014) gives these marks"),
        (context, "remarks"): d.text(REMARKS),
    }


MARK_VALUES = d.values({
    "laser": "a mark from a laser target designator",
    "infrared_pointer": "a mark from an infrared pointer. Aircrew with night vision devices can see it on the target",
    "smoke": "a mark from smoke ammunition at or near the target",
    "indirect_fire": "a mark from artillery, mortar or naval gun fire",
    "tracer": "a mark from tracer ammunition",
    "talk_on": "a talk-on, in which the controller tells the aircrew how to find the target by voice",
})


DESCRIPTIONS = {
    # ---- Shared parts ---------------------------------------------------------------------------
    ("ControllerContact", None): d.entity("Agency channel", "an agency for the aircrew, with its radio channels"),
    ("ControllerContact", "agency"): d.reference("agency", "the aircrew speaks to", "The agency is a controller, a JTAC or a different agency of the resource catalogue"),
    ("ControllerContact", "channel"): d.reference("primary " + CHANNEL, "connects the aircrew and the agency"),
    ("ControllerContact", "alternate_channel"): d.reference("alternative " + CHANNEL, "connects the aircrew and the agency when the primary channel is not available"),
    ("ReportingPlan", None): d.entity("Report plan", "the reports that an aircrew sends, with the method and the time of the reports"),
    ("ReportingPlan", "reports"): d.references("report definitions of the reports"),
    ("ReportingPlan", "recipient"): agency_ref("receives the reports"),
    ("ReportingPlan", "channel"): d.reference(CHANNEL, "is for the reports"),
    ("ReportingPlan", "method"): d.enum("method that the aircrew uses to send the reports"),
    ("ReportingPlan", "deadline"): d.time("before which the aircrew sends the reports"),
    ("BDARequirement", None): d.entity("BDA requirement", "the BDA that the aircrew collects after the attack"),
    ("BDARequirement", "method"): d.enum("method that the aircrew uses to collect the BDA"),
    ("BDARequirement", "report"): d.reference("report definition", "the aircrew uses to send the BDA"),
    ("BDARequirement", "recipient"): agency_ref("receives the BDA"),
    ("BDARequirement", "deadline"): d.time("before which the aircrew sends the BDA"),
    ("EmitterTarget", None): d.entity("Emitter target", "an emitter that is a target of the mission, with its priority"),
    ("EmitterTarget", "emitter"): d.reference("emitter", "is a target of the mission"),
    ("EmitterTarget", "target"): d.reference("target", "contains the emitter, when the resource catalogue has a target record for it"),
    ("EmitterTarget", "priority"): d.statement("This field gives the priority of this emitter", "Priority 1 is the highest"),
    ("CheckIn", None): d.entity("CAS check-in", "the data that the CAS aircrew gives to the controller at check-in",
                                "JP 3-09.3 (2014) Figure V-4 gives the check-in briefing"),
    ("CheckIn", "procedure"): procedure_ref("gives the check-in steps"),
    ("CheckIn", "items"): d.list_of("parts of the check-in briefing", "the aircrew gives"),
    ("CheckIn", "abort_code"): d.text("abort code for the controller and the aircrew"),
    ("Fuze", None): d.entity("Fuze setting", "the fuzes of a weapon, their function and their time adjustments",
                             "The `extensions.sim.dcs` data of a station keeps the DCS values of the fuze"),
    ("Fuze", "function"): d.enum("function of the fuze"),
    ("Fuze", "nose_fuze"): d.text("nose fuze of the weapon, such as `DSU-33`"),
    ("Fuze", "tail_fuze"): d.text("tail fuze of the weapon, such as `FMU-139`"),
    ("Fuze", "arming_delay_s"): d.quantity("time after the aircraft releases the weapon until the fuze can operate", None, "seconds"),
    ("Fuze", "delay_ms"): d.quantity("time after the weapon hits the target until the fuze functions", None, "milliseconds"),
    ("Fuze", "height_of_burst"): d.quantity("height above the ground at which the fuze functions", "Length"),
    ("WeaponLoad", None): d.entity("Weapon load", "the weapons of one flight for an attack assignment, with their fuze settings and altitudes"),
    ("WeaponLoad", "flight"): d.reference("flight", "releases the weapons"),
    ("WeaponLoad", "store"): d.reference("store", "is the weapon",
                                         d.enforced("When the flight has an SCL, an SCL of the flight shall contain the store",
                                                    "validator:openaix.check.scl.weapon_errors")),
    ("WeaponLoad", "scl"): d.reference("SCL", "contains the weapons",
                                       d.enforced("It shall be an SCL of the flight", "validator:openaix.check.scl.weapon_errors")),
    ("WeaponLoad", "quantity"): d.count("weapons for the flight",
                                        d.enforced("The quantity shall not be more than all aircraft of the flight have in their SCL",
                                                   "validator:openaix.check.scl.weapon_errors")),
    ("WeaponLoad", "fuze"): d.statement("This field gives the fuze setting of the weapons for this attack",
                                        "If the weapon load does not give it, the fuze of the store in the SCL of the flight is applicable"),
    ("WeaponLoad", "laser_code"): d.statement("This field gives the laser code of the weapons for this attack",
                                              "If the weapon load does not give it, the laser code of the SCL of the flight is applicable"),
    ("WeaponLoad", "release_altitude"): d.quantity("altitude at which the flight releases the weapons", "Altitude"),
    ("WeaponLoad", "attack_heading"): d.quantity("attack heading of the flight", "Bearing"),
    ("TargetListEntry", None): d.entity("Target list entry", "an entry on a JIPTL or on a TST list"),
    ("TargetListEntry", "document"): d.reference("JIPTL or TST document", "contains the entry"),
    ("TargetListEntry", "entry"): d.text("target number or TST number of the entry"),

    # ---- Briefs on each tasking -----------------------------------------------------------------
    ("OnCallCAS", "brief"): brief_field("on-call CAS tasking"),
    ("PreplannedAttack", "brief"): brief_field("preplanned attack"),
    ("Patrol", "brief"): brief_field("CAP"),
    ("CounterAir", "brief"): brief_field("counterair task"),
    ("Escort", "brief"): brief_field("escort"),
    ("Refueling", "brief"): brief_field("refuelling task"),
    ("AirborneControl", "brief"): brief_field("airborne control task"),
    ("Reconnaissance", "brief"): brief_field("reconnaissance task"),
    ("ElectromagneticTask", "brief"): brief_field("electromagnetic task"),
    ("Transport", "brief"): brief_field("transport task"),
    ("PersonnelRecovery", "brief"): brief_field("personnel recovery task"),
    ("Training", "brief"): brief_field("training task"),
    ("CustomTask", "brief"): brief_field("custom task"),
    ("CounterlandControl", "brief"): brief_field("counterland control task"),

    ("CASBrief", None): d.entity("CAS brief", "the data that CAS aircrews get before an on-call or scheduled CAS mission",
                                 "JP 3-09.3 (2014) Chapter V gives the check-in briefing and the CAS brief"),
    ("CASBrief", "check_in"): d.statement("This field gives the check-in data for the controller"),
    **cas_fields("CASBrief", "CAS mission"),

    ("AttackBrief", None): d.entity("Attack brief", "the data that aircrews get before a preplanned attack", "The role of the tasking gives the type of attack",
                                    "The attack assignments of the tasking give the targets, the effects, the times on target and the weapons"),
    ("AttackBrief", "initial_points"): d.references("initial points", "start the attack runs", role_rule("initial")),
    ("AttackBrief", "egress_points"): d.references("egress points or gates", "the flights fly through after the attack", role_rule("egress", "gate")),
    ("AttackBrief", "ingress_route"): d.reference("route", "the flights use to fly to the target area"),
    ("AttackBrief", "egress_route"): d.reference("route", "the flights use after the attack"),
    ("AttackBrief", "restricted_areas"): d.references("no-fire areas, restrictive fire areas or no-fly zones", "are applicable to the attack",
                                                      "Each no-strike site near a target has a no-fire area around it"),
    ("AttackBrief", "threat_emitters"): d.references("emitters", "can engage the flights on the route or at the target"),
    ("AttackBrief", "bda"): d.statement("This field gives the BDA that the aircrews collect after the attack"),
    ("AttackBrief", "sead"): d.statement("This field gives the SEAD data", "The field is applicable to SEAD and DEAD roles"),
    ("AttackBrief", "cas"): d.statement("This field gives the CAS data", "The field is applicable to the `scheduled_cas` role"),
    ("AttackBrief", "remarks"): d.text(REMARKS),
    ("SEADBrief", None): d.entity("SEAD brief", "the emitters for the suppression, the employment procedure and the missions that the suppression helps"),
    ("SEADBrief", "emitters"): d.list_of("threat emitters for the suppression, in order of priority"),
    ("SEADBrief", "employment_procedure"): procedure_ref("gives the employment and the ROE of the anti-radiation missiles"),
    ("SEADBrief", "protected_missions"): d.references("missions", "the suppression helps"),
    ("SEADBrief", "suppression_window"): d.window("the suppression of the threat emitters occurs"),

    ("CounterlandControl", None): d.entity("Counterland control task", "a SCAR or FAC(A) task in a specified area",
                                           "In a SCAR mission, the aircraft find targets and coordinate the attacks of other flights on them",
                                           "In a FAC(A) mission, the aircraft give terminal attack control to CAS aircraft",
                                           "SCAR aircraft do not have the authority of terminal attack control"),
    ("CounterlandControl", "kind"): tasking_kind("a counterland control tasking"),
    ("CounterlandControl", "mission_type"): d.enum("type of counterland control task: `scar` or `fac_a`"),
    ("CounterlandControl", "area"): task_area("in which the aircraft find targets and control the attacks"),
    ("CounterlandControl", "altitude"): d.altitude_block("the counterland control task"),
    ("CounterlandControl", "operating_window"): d.window("the aircraft are on station in the area"),
    ("CounterlandControl", "objective"): objective("counterland control task"),
    ("CounterlandControl", "success_criteria"): success_criteria("counterland control task"),
    ("CounterlandControl", "abort_criteria"): abort_criteria("counterland control task"),
    ("CounterlandControl", "report_refs"): report_refs("counterland control task"),
    ("SCARBrief", None): d.entity("SCAR brief", "the data for a SCAR mission"),
    ("SCARBrief", "controller"): contact("controls the sequence of the attack flights"),
    ("SCARBrief", "attack_missions"): d.references("attack missions", "the SCAR aircraft coordinate"),
    ("SCARBrief", "target_priorities"): d.list_of("types of target", "the SCAR aircraft look for, with their priorities"),
    ("SCARBrief.target_priorities", "category"): d.enum("type of target", "The values are openAIX values with no doctrinal source"),
    ("SCARBrief.target_priorities", "priority"): d.statement("This field gives the priority of the type of target", "Priority 1 is the highest"),
    ("SCARBrief", "entry_points"): d.references("points", "the attack flights fly through when they go into the area",
                                                role_rule("control", "ingress", "gate")),
    ("SCARBrief", "holding"): d.references("orbits, points or zones", "the attack flights use to hold"),
    ("SCARBrief", "stack"): d.list_of("altitude blocks of the holding stack, each for one attack mission"),
    ("SCARBrief.stack", "altitude"): d.altitude_block("this level of the stack"),
    ("SCARBrief.stack", "mission"): d.reference("attack mission", "holds at this level of the stack"),
    ("SCARBrief", "reporting"): d.statement("This field gives the reports of the SCAR aircraft, with the method and the time"),
    ("SCARBrief", "remarks"): d.text(REMARKS),
    ("FACABrief", None): d.entity("Forward air controller brief", "the data that the aircraft get before a FAC(A) mission"),
    ("FACABrief", "supported_unit"): d.text("name of the ground unit that the FAC(A) supports"),
    ("FACABrief", "cas_missions"): d.references("CAS missions", "the FAC(A) can control"),
    ("FACABrief", "terminal_control"): d.list_of("types of terminal attack control", "the FAC(A) can give"),
    **cas_fields("FACABrief", "FAC(A) mission"),

    ("AirToAirBrief", None): d.entity("Air-to-air brief", "the data for a CAP, a fighter sweep, an air intercept or an escort"),
    ("AirToAirBrief", "controller"): contact("controls the fighters, such as an AWACS"),
    ("AirToAirBrief", "bullseye"): d.reference("bullseye", "is the reference point of the controller and the fighters", role_rule("bullseye", single=True)),
    ("AirToAirBrief", "commit_criteria"): d.list_of("commit criteria", "start an engagement of an air track"),
    ("AirToAirBrief", "identification_procedure"): procedure_ref("gives the identification matrix and the ROE for air tracks"),
    ("AirToAirBrief", "roe_reference"): d.reference("part of the SPINS or of a different document", "gives the ROE"),
    ("AirToAirBrief", "protected_missions"): d.references("missions", "the fighters defend"),
    ("AirToAirBrief", "protected_measures"): d.references("orbits and areas", "the fighters defend, such as tanker and AWACS orbits"),
    ("AirToAirBrief", "threat_emitters"): d.references("surface-to-air emitters", "the fighters avoid"),
    ("AirToAirBrief", "remarks"): d.text(REMARKS),
    ("CommitCriterion", None): d.entity("Commit criterion", "a condition in which the fighters start an engagement of an air track",
                                        d.enforced("A commit criterion shall give a range, a boundary or a procedure", "schema:anyOf")),
    ("CommitCriterion", "threat"): d.reference("threat", "this commit criterion is for"),
    ("CommitCriterion", "range"): d.quantity("range from the fighters or from their defended asset at which they start the engagement", "Length"),
    ("CommitCriterion", "boundary"): d.reference("control measure", "is the boundary of this commit criterion"),
    ("CommitCriterion", "procedure"): procedure_ref("gives the full commit criteria"),

    ("RefuelingBrief", None): d.entity("Refuelling brief", "the data that tanker and receiver aircrews get before the refuelling",
                                       "The tasking gives the track, the altitude block, the refuelling method, the channel, the TACAN and the receivers"),
    ("RefuelingBrief", "anchor"): d.reference("orbit, point or air-to-air refuelling area", "is the anchor of the refuelling track"),
    ("RefuelingBrief", "rendezvous"): d.enum("type of rendezvous between the tanker and the receivers",
                                             "The values are openAIX values with no doctrinal source"),
    ("RefuelingBrief", "rendezvous_point"): d.reference("point", "is the rendezvous point of the tanker and the receivers"),
    ("RefuelingBrief", "control_time"): d.time("at which the tanker and the first receiver are at the rendezvous point"),
    ("RefuelingBrief", "receiver_altitude"): d.quantity("altitude at which the receivers join the tanker", "Altitude"),
    ("RefuelingBrief", "remarks"): d.text(REMARKS),

    ("AirborneControlBrief", None): d.entity("Airborne control brief", "the data that an airborne control aircrew gets before the mission"),
    ("AirborneControlBrief", "orbit"): d.reference("orbit or airborne early warning area", "is the station of the control aircraft"),
    ("AirborneControlBrief", "controlled_channels"): d.references("radio channels", "the control aircraft uses to control flights"),
    ("AirborneControlBrief", "bullseye"): d.reference("bullseye", "is the reference point of the controllers", role_rule("bullseye", single=True)),
    ("AirborneControlBrief", "sectors"): d.list_of("control sectors of the control aircraft"),
    ("AirborneControlBrief", "handover_points"): d.references("points", "flights change controller at", role_rule("handover", "control")),
    ("AirborneControlBrief", "remarks"): d.text(REMARKS),
    ("ControlSector", None): d.entity("Control sector", "a part of the airspace that one controller of the control aircraft controls"),
    ("ControlSector", "name"): d.name("control sector"),
    ("ControlSector", "area"): task_area("that is the sector"),
    ("ControlSector", "altitude"): d.altitude_block("the control sector"),
    ("ControlSector", "channel"): d.reference(CHANNEL, "is for the controller of the sector"),
    ("ControlSector", "flights"): d.references("flights", "the controller of the sector controls"),
    ("ControlSector", "missions"): d.references("missions", "the controller of the sector controls"),

    ("ReconnaissanceBrief", None): d.entity("Reconnaissance brief", "the data for a reconnaissance mission",
                                            "The collection entries of the tasking give the information, the sensors and the times"),
    ("ReconnaissanceBrief", "named_areas"): d.references("named areas of interest, target areas of interest or reconnaissance areas", "the aircraft look at"),
    ("ReconnaissanceBrief", "reporting"): d.statement("This field gives the reports of the reconnaissance aircraft, with the method and the time"),
    ("ReconnaissanceBrief", "remarks"): d.text(REMARKS),
    ("CollectionRequirement", "eeis"): d.list_of("EEIs of this collection"),
    ("CollectionRequirement.eeis", "id"): d.identifier("EEI", "its collection entry"),
    ("CollectionRequirement.eeis", "question"): d.text("text of the EEI"),
    ("CollectionRequirement.eeis", "priority"): d.statement("This field gives the priority of the EEI", "Priority 1 is the highest"),
    ("CollectionRequirement", "reporting"): d.statement("This field gives the method and the time of the reports for this collection"),

    ("ElectromagneticBrief", None): d.entity("Electromagnetic brief", "the data for an electromagnetic attack mission"),
    ("ElectromagneticBrief", "emitters"): d.list_of("threat emitters for the electromagnetic attack, in order of priority"),
    ("ElectromagneticBrief", "orbit"): d.reference("orbit or zone", "is the station of the aircraft during the electromagnetic attack"),
    ("ElectromagneticBrief", "protected_channels"): d.references("radio channels", "stay clear of the electromagnetic attack"),
    ("ElectromagneticBrief", "remarks"): d.text(REMARKS),

    ("TransportBrief", None): d.entity("Transport brief", "the data for a transport mission"),
    ("TransportBrief", "onload"): d.statement("This field gives the airfield, the time and the procedure at which the load goes into the aircraft"),
    ("TransportBrief", "offload"): d.statement("This field gives the airfield, the time and the procedure at which the load goes out of the aircraft"),
    ("TransportBrief", "load_plan"): d.list_of("loads of the flights"),
    ("TransportBrief.load_plan", "flight"): d.reference("flight", "has this load"),
    ("TransportBrief.load_plan", "manifest"): d.statement("This field gives the cargo and the passengers of this load"),
    ("TransportBrief", "patients"): d.statement("This field gives the numbers of patients and attendants for the `aeromedical_evacuation` role"),
    ("TransportBrief.patients", "litter"): d.count("patients on litters"),
    ("TransportBrief.patients", "ambulatory"): d.count("patients that can walk"),
    ("TransportBrief.patients", "attendants"): d.count("medical attendants"),
    ("TransportBrief", "airdrop"): d.statement("This field gives the airdrop data",
                                               d.enforced("A transport task with the `airdrop` role shall have this field", "schema:then")),
    ("TransportBrief", "air_assault"): d.statement("This field gives the air assault data",
                                                   d.enforced("A transport task with the `air_assault` role shall have this field", "schema:then")),
    ("TransportBrief", "remarks"): d.text(REMARKS),
    ("TransferPoint", None): d.entity("Load point", "an airfield where the load goes into or out of the aircraft, with the time and the procedure"),
    ("TransferPoint", "place"): d.reference("airfield, carrier or FARP", "receives or sends the load"),
    ("TransferPoint", "window"): d.window("the load goes into or out of the aircraft"),
    ("TransferPoint", "procedure"): procedure_ref("gives the steps for the load"),
    ("TransferPoint", "agency"): agency_ref("controls the operations with the load"),

    ("AirdropBrief", None): d.entity("Airdrop brief", "the data for an airdrop mission",
                                     "FM 3-99 (2015) Chapter 5 and FM 3-21.38 (2006) Chapter 6 give these data"),
    ("AirdropBrief", "drop_zone"): d.reference("DZ", "receives the airdrop"),
    ("AirdropBrief", "run_in_heading"): d.quantity("heading of the aircraft on the run-in to the DZ", "Bearing"),
    ("AirdropBrief", "release_method"): d.enum("method that sets the release point"),
    ("AirdropBrief", "release_point"): d.reference("point", "is the release point in the plan"),
    ("AirdropBrief", "point_of_impact"): d.reference("point", "is the point of impact on the DZ"),
    ("AirdropBrief", "drop_altitude"): d.quantity("altitude at which the aircraft release the load", "Altitude"),
    ("AirdropBrief", "drop_airspeed"): d.statement("This field gives the airspeed at which the aircraft release the load, with its unit"),
    ("AirdropBrief", "load_type"): d.enum("type of the load"),
    ("AirdropBrief", "parachute_technique"): d.enum("parachute method of the personnel drop"),
    ("AirdropBrief", "markings"): d.list_of("markings of the DZ that the aircrew looks for"),
    ("AirdropBrief", "code_letter"): d.statement("This field gives the code letter on the DZ, as one letter from `A` to `Z`"),
    ("AirdropBrief", "clear_to_drop_signal"): d.enum("signal that gives the clearance to release the load"),
    ("AirdropBrief", "authentication_procedure"): procedure_ref("gives the authentication between the aircrew and the DZ support team"),
    ("AirdropBrief", "drop_window"): d.window("the aircraft release the load"),
    ("AirdropBrief", "drop_zone_controller"): contact("controls the DZ"),
    ("AirdropBrief", "remarks"): d.text(REMARKS),

    ("AirAssaultBrief", None): d.entity("Air assault brief", "the data that air assault aircrews get before the mission",
                                        "FM 3-99 (2015) Chapters 12 and 13 give the air movement table and the lifts, serials and chalks"),
    ("AirAssaultBrief", "pickup_zones"): d.references("PZs", "the troops go into the aircraft at"),
    ("AirAssaultBrief", "landing_zones"): d.references("LZs", "the troops go out of the aircraft at"),
    ("AirAssaultBrief", "h_hour"): d.time("at which the first serial is on the LZ"),
    ("AirAssaultBrief", "air_movement_table"): d.list_of("lines of the air movement table", None, ordered=True),
    ("AirAssaultBrief", "routes"): d.references("routes", "the serials fly between the PZs and the LZs"),
    ("AirAssaultBrief", "corridors"): d.references("air corridors and transit routes", "are for the serials"),
    ("AirAssaultBrief", "escort_missions"): d.references("escort and attack missions", "defend the serials"),
    ("AirAssaultBrief", "remarks"): d.text(REMARKS),
    ("AirMovementLine", None): d.entity("Air movement line", "one line of the air movement table, for one serial of one lift",
                                        "FM 3-99 (2015) paragraph 12-37 gives the data of the line"),
    ("AirMovementLine", "line"): d.count("the line in the air movement table"),
    ("AirMovementLine", "lift"): d.count("the lift of the line"),
    ("AirMovementLine", "serial"): d.count("the serial in the lift"),
    ("AirMovementLine", "chalks"): d.list_of("chalk numbers of the aircraft in the serial"),
    ("AirMovementLine", "flight"): d.reference("flight", "flies the serial"),
    ("AirMovementLine", "lifted_unit"): d.text("name of the unit in the serial"),
    ("AirMovementLine", "pickup_zone"): d.reference("PZ", "the serial loads at"),
    ("AirMovementLine", "load_time"): d.time("at which the troops go into the aircraft at the PZ"),
    ("AirMovementLine", "takeoff_time"): d.time("of the departure of the serial from the PZ"),
    ("AirMovementLine", "start_point"): d.reference("start point", "the serial flies through after the PZ"),
    ("AirMovementLine", "start_point_time"): d.time("at which the serial is at the start point"),
    ("AirMovementLine", "release_point"): d.reference("release point", "the serial flies through before the LZ"),
    ("AirMovementLine", "release_point_time"): d.time("at which the serial is at the release point"),
    ("AirMovementLine", "landing_zone"): d.reference("LZ", "is the end of the flight of the serial"),
    ("AirMovementLine", "landing_time"): d.time("at which the serial is on the LZ"),
    ("AirMovementLine", "landing_heading"): d.quantity("heading of the serial when it lands", "Bearing"),
    ("AirMovementLine", "landing_formation"): d.enum("formation of the serial when it lands"),
    ("AirMovementLine", "route"): d.reference("route", "is for the serial"),
    ("AirMovementLine", "load"): d.statement("This field gives the personnel and the cargo of the serial"),
    ("AirMovementLine", "remarks"): d.text("notes about this serial, such as a change of time"),

    ("PersonnelRecoveryBrief", None): d.entity("Personnel recovery brief", "the data that a recovery aircrew gets before the mission",
                                               "The brief identifies the ISOPREP of a survivor and contains no other data about the person"),
    ("PersonnelRecoveryBrief", "survivors"): d.list_of("isolated persons for this recovery"),
    ("PersonnelRecoveryBrief", "on_scene_commander"): d.reference("flight", "is the on-scene commander"),
    ("PersonnelRecoveryBrief", "rescort_missions"): d.references("RESCORT missions", "defend the recovery"),
    ("PersonnelRecoveryBrief", "holding"): d.references("orbits, points or zones", "the recovery flights use to hold"),
    ("PersonnelRecoveryBrief", "ingress_route"): d.reference("route", "the recovery flights use to fly to the objective area"),
    ("PersonnelRecoveryBrief", "egress_route"): d.reference("route", "the recovery flights use after the recovery"),
    ("PersonnelRecoveryBrief", "pickup_window"): d.window("the recovery flights plan to be at the survivors"),
    ("PersonnelRecoveryBrief", "remarks"): d.text(REMARKS),
    ("Survivor", None): d.entity("Survivor", "an isolated person for this recovery"),
    ("Survivor", "id"): d.identifier("survivor", "its brief"),
    ("Survivor", "callsign"): d.text("call sign of the survivor"),
    ("Survivor", "last_known"): d.statement("This field gives the last known position of the survivor and the time of the report"),
    ("Survivor", "condition"): d.enum("medical condition of the survivor"),
    ("Survivor", "isoprep_ref"): d.text("identifier of the ISOPREP of the survivor",
                                        "The brief contains only this identifier and no other data about the person"),
    ("Survivor", "authentication_procedure"): procedure_ref("gives the authentication of the survivor"),

    ("TrainingBrief", None): d.entity("Training brief", "the data that aircrews get before a training task"),
    ("TrainingBrief", "range_controller"): contact("controls the training range"),
    ("TrainingBrief", "knock_it_off_channel"): d.reference(CHANNEL, "is for safety calls"),
    ("TrainingBrief", "minimum_altitude"): d.quantity("lowest altitude for the training", "Altitude"),
    ("TrainingBrief", "safety_procedure"): procedure_ref("gives the safety instructions of the training"),
    ("TrainingBrief", "training_areas"): d.references("training areas, zones and airspace", "are for the training"),
    ("TrainingBrief", "remarks"): d.text(REMARKS),

    ("CustomBrief", None): d.entity("Custom brief", "a set of values with names for a custom task, with the namespace of the application that gives the values"),
    ("CustomBrief", "namespace"): d.text("namespace of the application or standard that gives the data, such as `org.example.task`"),
    ("CustomBrief", "schema"): d.reference("schema", "validates the data"),
    ("CustomBrief", "data"): d.statement("This field contains the data of the brief, as values with names"),
    ("CustomBrief", "remarks"): d.text(REMARKS),

    # ---- Attack assignments ---------------------------------------------------------------------
    ("AttackAssignment", "weaponeering"): d.list_of("weapon loads of the flights for this attack assignment"),
    ("AttackAssignment", "target_list_entry"): d.statement("This field gives the JIPTL or TST entry of the target of this attack assignment"),

    # ---- Report definitions in the resource catalogue -----------------------------------------
    ("resources:ReportDefinition", "classification"): d.enum("highest security classification of the data in the report"),
    ("resources:ReportDefinition", "medium"): d.enum("transmission method of the report"),
    ("resources:ReportDefinition", "recipient"): d.reference("command and control agency", "receives the report"),
    ("resources:ReportDefinition", "channel"): d.reference("radio channel", "is for the report"),

    # ---- Emitters in the resource catalogue -----------------------------------------------------
    ("ResourceData", "emitters"): d.map_of("emitters, which are air defence radars with their systems and threat rings"),
    ("Threat", "emitters"): d.references("emitters", "are a part of this threat"),
    ("Emitter", None): d.entity("Emitter", "an air defence radar with the system that it is a part of, its position and its threat ring",
                                "Briefs and orders refer to the emitter by its identifier and do not copy it",
                                "A consumer shows the threat ring as a circle around the position of the emitter",
                                d.enforced("An emitter shall have a position or simulator bindings", "schema:anyOf")),
    ("Emitter", "id"): d.identifier("emitter", "the resource catalogue", "Briefs, threats and orders use it to refer to this emitter"),
    ("Emitter", "name"): d.name("emitter site, such as `Cobalt SA-6 battery`"),
    ("Emitter", "system_id"): d.text("NATO designation of the weapon system, such as `SA-6`"),
    ("Emitter", "reporting_name"): d.text("NATO reporting name of the weapon system, such as `Gainful`"),
    ("Emitter", "native_designation"): d.text("designation of the weapon system in the armed forces that operate it, such as `2K12 Kub`"),
    ("Emitter", "radar_reporting_name"): d.text("NATO reporting name of the radar, such as `Straight Flush`"),
    ("Emitter", "radar_system_id"): d.text("designation of the radar, such as `1S91`", "Many radars have only a reporting name"),
    ("Emitter", "radar_roles"): d.list_of("functions of the radar in its air defence unit", None,
                                          "Appendix B of the `DCS F-16C Early Access Guide` gives these types"),
    ("Emitter", "rwr_symbol"): d.text("symbol that the RWR shows for the radar, for display"),
    ("Emitter", "position"): d.position("the emitter", "For a mobile emitter, the position is the position from the last report"),
    ("Emitter", "status"): d.enum("condition of the emitter from the last report"),
    ("Emitter", "last_seen"): d.time("of the last report of the emitter"),
    ("Emitter", "mobility"): d.enum("mobility of the emitter"),
    ("Emitter", "side"): d.enum("coalition of the emitter"),
    ("Emitter", "max_engagement_range"): d.quantity("largest range at which the system can engage an aircraft", "Length",
                                                    "This range is the radius of the threat ring"),
    ("Emitter", "min_engagement_range"): d.quantity("smallest range at which the system can engage an aircraft", "Length",
                                                    d.enforced("This range shall be smaller than the largest engagement range", "validator:openaix.check.emitters.document")),
    ("Emitter", "detection_range"): d.quantity("largest range at which the radar can find an aircraft", "Length"),
    ("Emitter", "engagement_floor"): d.vertical_limit("floor", "the engagement envelope of the system"),
    ("Emitter", "engagement_ceiling"): d.vertical_limit("ceiling", "the engagement envelope of the system"),
    ("Emitter", "measures"): d.references("missile engagement zones, missile arcs and the other measures of air defence", "are for this emitter",
                                          d.enforced("Each missile arc shall start at the emitter, and each engagement zone shall contain it",
                                                     "validator:openaix.check.emitters.document")),
    ("Emitter", "remarks"): d.text("notes about the emitter"),

    # ---- Target lists ---------------------------------------------------------------------------
    ("tst", "resources_ref"): d.reference("external resource catalogue", "resolves the references of the list",
                                          "The reference identifies the catalogue and gives its revision"),
    ("jiptl", "resources_ref"): d.reference("external resource catalogue", "resolves the references of the list",
                                            "The reference identifies the catalogue and gives its revision"),
    ("TSTEntry", "target"): d.reference("target", "is this entry, in the resource catalogue"),
    ("JIPTLTarget", "target"): d.reference("target", "is this entry, in the resource catalogue"),
    ("TSTEntry", "expires_at"): d.time("at which the target goes off the list, if no other condition removes it first"),
    ("EngagementMeans", None): d.entity("Approved weapon system", "a weapon system or an aircraft type that has clearance to engage the target, with its weapon"),
    ("EngagementMeans", "system"): d.text("weapon system or type of aircraft, such as `F-15E`, `M777` or `HIMARS`"),
    ("EngagementMeans", "scl"): d.reference("SCL", "is the load of the aircraft"),
    ("EngagementMeans", "store"): d.reference("store", "is the weapon",
                                              d.enforced("When the entry gives an SCL, the SCL shall contain the store",
                                                         "validator:openaix.check.scl.engagement_errors")),
}


ENUMS = {
    ("Emitter", "status"): d.values({"active": "an emitter that transmits", "silent": "an emitter that does not transmit at this time",
                                     "suspected": "an emitter that one report gives and that no other source agrees with",
                                     "destroyed": "an emitter that an assessment shows as destroyed"}),
    ("Emitter", "mobility"): d.values({"fixed": "a system that does not move", "mobile": "a system that can fire while it moves or a short time after it stops",
                                       "relocatable": "a system that can fire only from a fire position, after it moves there"}),
    ("CounterlandControl", "mission_type"): d.values({
        "scar": d.value("SCAR", "Aircraft find targets in a specified area and coordinate the attacks of other flights on them"),
        "fac_a": d.value("a FAC(A) mission", "A FAC(A) gives terminal attack control to CAS aircraft from the air"),
    }),
    ("CASBrief", "marks"): MARK_VALUES,
    ("FACABrief", "marks"): MARK_VALUES,
    ("CheckIn", "items"): d.values({
        "mission_number": "the mission number of the flight in the ATO",
        "aircraft_number_and_type": "the quantity of aircraft in the flight and their aircraft type",
        "position_and_altitude": "the position of the flight at this time, usually from a control point, and its altitude",
        "ordnance": "the weapons on the aircraft, with the quantity of each",
        "time_on_station": "the time that the aircraft can stay on station", "capabilities": "the sensors and the other capabilities of the aircraft",
        "abort_code": "the code that the aircrew uses to make sure that an abort call comes from the controller",
    }),
    ("AirdropBrief", "release_method"): d.values({
        "carp": "a CARP that the aircrew calculates",
        "harp": "a HARP for a HALO or HAHO personnel drop",
        "gmrs": "a GMRS, in which markings on the ground show the release point",
        "virs": "a VIRS, in which the DZ support team tells the aircrew when to release",
    }),
    ("AirdropBrief", "load_type"): d.values({
        "personnel": "a drop of troops or other personnel with parachutes",
        "heavy_equipment": "a heavy drop of vehicles or equipment on platforms",
        "container_delivery_system": d.value("an airdrop of supplies in containers",
                                             "The containers go out of the rear of the aircraft in sequence, because of their weight"),
        "door_bundle": "a small load that the aircrew pushes out of a door at the side of the aircraft",
        "precision_airdrop": "an airdrop in which a guidance system moves the parachute of each load to the point of impact",
    }),
    ("AirdropBrief", "parachute_technique"): d.values({
        "static_line": d.value("a parachute drop at low altitude",
                               "A line in the aircraft opens each parachute when the person goes out of the aircraft"),
        "halo": d.value("a HALO personnel drop",
                        "The personnel go out of the aircraft at high altitude and open their parachutes at low altitude"),
        "haho": d.value("a HAHO personnel drop",
                        "The personnel open their parachutes at high altitude a short time after they go out of the aircraft",
                        "Then they fly a long distance to the DZ with their parachutes"),
    }),
    ("AirdropBrief", "markings"): d.values({
        "raised_angle_marker": "a raised angle marker at the point of impact", "code_letter": d.value("a large letter on the ground at the DZ",
                                                                                     "The aircrew compares it with the code letter of the brief to make sure that "
                                                                                     "the DZ is correct"),
        "panels": "panels with bright colours on the ground that show the DZ to the aircrew",
        "lights": "marker lights on the ground that show the DZ to the aircrew, usually at night",
        "smoke": "smoke on the ground that shows the DZ and the wind direction to the aircrew",
    }),
}
