"""ATO, ACO, TST, JIPTL, resource, agency and controller descriptions. Keys follow describe/resolve.py; every value is a describe/templates.py template."""
from openaix.describe import templates as d


SUBJECTS = {
    "TSTEntry": "time-sensitive target entry",
    "JIPTLTarget": "target entry",
    "VoxJTACSettings": "group of JTAC values",
}


def acmreq(set_name):
    """Two note sentences: the field agrees with one set of the ACMREQ message, without a claim of full agreement."""
    return ("This field agrees with the `" + set_name + "` set of the ACMREQ message in AJP-3.3.5 Annex C",
            "openAIX does not tell that the order agrees fully with the ACO message standard")


def stable_id(subject):
    """Identifier of an object that other records refer to."""
    return d.identifier(subject, None, "Other records and orders use it to refer to this " + subject)


GO_DURATION = "The value is a time interval in the Go format, such as `500ms`"
SCHEMA_ID = d.reference("schema", "validates this document")
SOURCE = d.reference("source document", None, "The reference identifies the document",
                     "It may also give a revision and a locator")
MGRS = d.text("same position for display, in the MGRS",
              "If the two values are different, the geographic position has priority")
EXCLUSIVE = d.enforced("The order shall have `resources` or `resources_ref`, but not the two fields", "schema:oneOf")


def resources_inline(what):
    return d.statement("This field contains a resource catalogue in the order",
                       "The catalogue resolves the " + what + " of the order", EXCLUSIVE)


RESOURCES_REF = d.reference("external resource catalogue", "resolves the references of the order",
                            "More than one document can use the same catalogue",
                            "The reference identifies the catalogue and gives its revision", EXCLUSIVE)
EXTERNAL_REF = d.reference("external resource catalogue", "resolves the references of this record",
                           "The reference identifies the catalogue and gives its revision")


DESCRIPTIONS = {
    # ---- ACO ------------------------------------------------------------------------------------
    ("aco", None): d.root("Airspace control order", "ACO",
                          "an order that activates or deactivates control measures for a specified period",
                          "It also gives the function and the restrictions of each control measure that it refers to"),
    ("aco", "$schema"): SCHEMA_ID,
    ("aco", "assignments"): d.list_of("instructions with a time limit",
                                      "activate control measures or deactivate them, or give them a function, in the order period"),
    ("aco.assignments", "role"): d.enum("mission or service for which the assignment keeps an orbit",
                                        "The ATO, and not this order, tasks the service",
                                        "Examples are the refuelling method of the tanker, the TACAN, the receivers and the surveillance task"),
    ("aco.assignments", "control_points"): d.references("reference points, control points or rendezvous points", "this assignment uses",
                                                        "Their coordinates stay in the catalogue of control measures", *acmreq("CNTRLPT")),
    ("aco.assignments", "controlling_agency"): d.reference("agency", "controls the control measure during this assignment",
                                                           "The standing agency of the control measure does not change",
                                                           *acmreq("CONTAUTH")),
    ("aco.assignments", "effective"): d.window("this assignment is in effect", "The interval is in the order period", *acmreq("APERIOD")),
    ("aco.assignments", "entry_route"): d.reference("route", "aircraft use to go into the holding pattern of the assignment"),
    ("aco.assignments", "exit_route"): d.reference("route", "aircraft use to go out of the holding pattern of the assignment"),
    ("aco.assignments", "extensions"): d.extension(),
    ("aco.assignments", "killbox_status"): d.enum("firing condition of a kill box for the `effective` interval: `open` or `closed`",
                                                  "The order gives this condition",
                                                  "A kill box is open from its activation until it closes or until an order cancels it",
                                                  "As a result, when an active assignment of a kill box does not have this field, the kill box stays open"),
    ("aco.assignments", "measure"): d.reference("control measure", "this assignment is for", *acmreq("ACMID")),
    ("aco.assignments", "purpose"): d.text("operation that this assignment is for", *acmreq("GENTEXT PURPOSE")),
    ("aco.assignments", "restrictions"): d.list_of("restrictions that this assignment adds"),
    ("aco.assignments", "stack_instructions"): d.list_of("procedures of the holding stack for an orbit with the `holding` role"),
    ("aco.assignments", "state"): d.enum("condition that the order gives to this assignment for the `effective` interval: `active` or `deactivated`",
                                         "The value `active` shows that the assignment is in effect",
                                         "It is not the active condition of a kill box, which is an open kill box with aircraft in it"),
    ("aco.assignments", "transit_instructions"): d.list_of("instructions for aircraft that go into, go through or go out of the control measure during the assignment",
                                                           None, *acmreq("GENTEXT TRANSIT INSTRUCTIONS")),
    ("aco.assignments", "usage"): d.enum("function of the control measure during this assignment, for the filters of controllers and planners",
                                         "The values are openAIX values and not a code list of a message standard"),
    ("aco", "extensions"): d.extension(),
    ("aco", "instructions"): d.list_of("general instructions for airspace control that are applicable to the full order"),
    ("aco", "period"): d.window("the order is in effect", "Each assignment is in this interval"),
    ("aco", "references"): d.list_of("coordination documents for the order, such as the airspace control plan, the ATO or the SPINS"),
    ("aco", "resources"): resources_inline("references to control measures, agencies, channels and routes"),
    ("aco", "resources_ref"): RESOURCES_REF,

    # ---- ATO ------------------------------------------------------------------------------------
    ("ato", None): d.root("Air tasking order", "ATO",
                          "an order that tasks missions and gives their flights and packages",
                          "It also gives the control of the missions and the resources that help them"),
    ("ato", "$schema"): SCHEMA_ID,
    ("ato", "aco"): d.reference("ACO", "this ATO coordinates with", "The reference identifies a document", "It does not activate airspace"),
    ("ato", "extensions"): d.extension(),
    ("ato", "general_instructions"): d.list_of("instructions", "are applicable to all missions in the order"),
    ("ato", "missions"): d.list_of("missions that the order tasks", None,
                                   "Each mission has a mission number, one typed tasking and the flights that the order gives to it"),
    ("ato", "packages"): d.list_of("packages", "contain missions that fly together for one objective"),
    ("ato", "period"): d.window("the order tasks missions"),
    ("ato", "resources"): resources_inline("references"),
    ("ato", "resources_ref"): RESOURCES_REF,
    ("ato", "spins"): d.reference("SPINS publication", "is applicable to this order",
                                  "The reference identifies the publication and one revision of it"),

    ("Activity", "altitude"): d.quantity("altitude at which the flight can do this operation", "Altitude"),
    ("Activity", "description"): d.text("data about this operation and its local conditions"),
    ("Activity", "id"): stable_id("flight operation"),
    ("Activity", "instructions"): d.list_of("instructions for this flight operation"),
    ("AirborneControl", "altitude"): d.altitude_block("this airborne control task"),
    ("AirborneLaunch", "altitude"): d.quantity("altitude that the order gives for the airborne launch", "Altitude"),
    ("AirborneLaunch", "position"): d.position("the airborne launch"),
    ("AlertLaunch", "availability"): d.window("the alert launch is available"),
    ("AttackAssignment", "id"): stable_id("attack assignment"),
    ("AttackAssignment", "instructions"): d.list_of("instructions for this attack assignment"),
    ("AttackAssignment", "restrictions"): d.list_of("limits and conditions that are applicable to this attack assignment"),
    ("CargoItem", "name"): d.name("cargo item"),
    ("CollectionRequirement", "id"): stable_id("collection entry"),
    ("CounterAir", None): d.entity("Counterair task", "a fighter sweep or an air intercept",
                                   d.enforced("A fighter sweep shall have an operating area", "schema:then"),
                                   d.enforced("An air intercept shall identify a target, or the area where the fighters contact the target",
                                              "schema:else"),
                                   "CAP is a different type of tasking"),
    ("CounterAir", "mission_type"): d.enum("type of counterair task: `fighter_sweep` or `interception`"),
    ("CounterAir", "abort_criteria"): d.list_of("conditions in which the fighters stop the task"),
    ("CounterAir", "altitude"): d.altitude_block("the counterair task"),
    ("CounterAir", "area"): d.reference("area or airspace", "contains the fighter sweep or the air intercept"),
    ("CounterAir", "engagement_instructions"): d.reference("procedure", "gives the commit criteria and the engagement conditions"),
    ("CounterAir", "objective"): d.text("result that the counterair task is for"),
    ("CounterAir", "operating_window"): d.window("the fighter sweep or the air intercept occurs, as the plan gives it"),
    ("CounterAir", "report_refs"): d.references("reports", "the task sends"),
    ("CounterAir", "success_criteria"): d.text("conditions that show a satisfactory result of the task"),
    ("CounterAir", "target"): d.reference("mobile target", "is the aircraft or the formation for the air intercept",
                                          "The target is not always an enemy",
                                          "Its position and simulator bindings stay on the target record"),
    ("CustomTask", "extensions"): d.extension(),
    ("CustomTask", "name"): d.name("custom task"),
    ("ElectromagneticTask", "restrictions"): d.list_of("limits and conditions that are applicable to this electromagnetic task"),
    ("Escort", "rendezvous"): d.reference("control point", "is the rendezvous point of the escort and the missions that it gives protection to"),
    ("Flight", "extensions"): d.extension(),
    ("Flight", "id"): stable_id("flight"),
    ("Flight", "notes"): d.text("notes about this flight"),
    ("Flight", "route"): d.reference("route", "this flight follows"),
    ("FuelPlan", "notes"): d.text("notes about this fuel plan"),
    ("Identification", "instructions"): d.list_of("instructions for identification"),
    ("Mission", None): d.entity("Mission", "a task that the order gives, with a mission number, one typed tasking and the flights for it",
                                "The consumer keeps the condition of the allocation and of the execution"),
    ("Mission", "extensions"): d.extension(),
    ("Mission", "flights"): d.list_of("flights that the order gives to the mission", None,
                                      "When the list is empty, the tasking has no allocation"),
    ("Mission", "id"): stable_id("mission"),
    ("Mission", "mission_number"): d.identifier("mission", "the order",
                                                "Units use the mission number to refer to the mission on kneeboards and by voice"),
    ("Mission", "tasking"): d.statement("This field gives the one typed tasking of this mission"),
    ("OnCallCAS", None): d.entity("On-call CAS tasking",
                                  "a tasking for the on-call type of preplanned close air support, or for immediate close air support",
                                  "JP 3-09.3 (2014) paragraph 27 gives these types",
                                  "On-call aircraft wait on ground alert or airborne alert until they get a request",
                                  "Immediate close air support is for requests that are not in the plan"),
    ("PreplannedAttack", "role"): d.enum("attack role of this preplanned attack",
                                         "The value `scheduled_cas` is for CAS at a scheduled time",
                                         "On-call CAS and immediate close air support use the tasking for on-call CAS"),
    ("AttackAssignment", "desired_effect"): d.enum("effect on the target that the attack assignment gives",
                                                   "The values are openAIX values with no doctrinal source"),
    ("OnCallCAS", "availability"): d.window("the on-call CAS is available"),
    ("Package", "extensions"): d.extension(),
    ("Package", "id"): stable_id("package"),
    ("Package", "name"): d.name("package"),
    ("Package", "rendezvous"): d.reference("control point", "is the rendezvous point of the package"),
    ("Patrol", "altitude"): d.altitude_block("the patrol"),
    ("PersonnelRecovery", "availability"): d.window("the personnel recovery asset is available"),
    ("PersonnelRecovery", "role"): d.enum("role of the personnel recovery: SAR or CSAR",
                                          "The role is different from the recovery method",
                                          "The role does not make a control measure"),
    ("RadioAssignment", "purpose"): d.text("operation or objective of this radio assignment"),
    ("Recovery", "restrictions"): d.list_of("limits and conditions that are applicable to this recovery"),
    ("Refueling", "altitude"): d.altitude_block("the refuelling task"),
    ("Refueling", "method"): d.enum("refuelling systems that the tanker supplies for this tasking: `boom`, `drogue` (probe and drogue) or `both`"),
    ("Refueling", "receivers"): d.list_of("receiver flights in the schedule of the tanker, with their windows and the fuel that the tanker plans to give"),
    ("Refueling", "tacan"): d.statement("This field gives the channel, band and identifier of the TACAN of the tanker for this tasking, in air-to-air mode"),
    ("SelfControl", "instructions"): d.text("instructions for self control"),
    ("Training", "restrictions"): d.list_of("limits and conditions that are applicable to this training"),
    ("Transport", "role"): d.enum("function of the transport mission",
                                  "The field `delivery_method` gives how the load goes out of the aircraft"),

    # ---- Command and control agency -------------------------------------------------------------
    ("c2-agency", None): d.root("Command and control agency", None,
                                "an organization with a call sign and a role in operations", "Units contact it on its radio channels"),
    ("c2-agency", "$schema"): SCHEMA_ID,
    ("c2-agency", "callsign"): d.text("radio call sign of the agency"),
    ("c2-agency", "channels"): d.references("radio channels", "other units use to contact the agency"),
    ("c2-agency", "extensions"): d.extension(),
    ("c2-agency", "id"): stable_id("agency"),
    ("c2-agency", "kind"): d.discriminator("a command and control agency"),
    ("c2-agency", "position"): d.position("the agency", "The field is applicable only to an agency that does not move"),
    ("c2-agency", "resources_ref"): EXTERNAL_REF,
    ("c2-agency", "role"): d.enum("command and control function of the agency"),

    # ---- Forward air controller -----------------------------------------------------------------
    ("fac", None): d.root("Forward air controller", "FAC",
                          "a record of a FAC, a JTAC or a FAC(A)",
                          "It contains the role, the platform, the communications and the control functions of the controller"),
    ("fac", "$schema"): SCHEMA_ID,
    ("fac", "callsign"): d.text("radio call sign of the controller"),
    ("fac", "channels"): d.references("radio channels", "the controller uses"),
    ("fac", "coalition"): d.enum("coalition of the controller in the simulation"),
    ("fac", "coordinate_source"): d.enum("method that the controller uses to get target coordinates",
                                         "The value is not a type of target location error"),
    ("fac", "default_laser_code"): d.quantity("laser code that the controller uses when the brief gives no other code", "LaserCode"),
    ("fac", "egress_points"): d.references("egress points", "the controller gives to aircraft",
                                           "Each one refers to a point with the role egress, gate or fix"),
    ("fac", "equipment"): d.list_of("equipment items that the controller or the observer team has", None,
                                    "When an item is not in the list, the list does not add or remove that equipment"),
    ("fac.equipment", "available"): d.flag("this equipment is available for the operation in the plan"),
    ("fac.equipment", "horizontal_accuracy"): d.quantity("horizontal precision of the equipment that its data gives", "Length",
                                                         "The value is not an assessment of the error for each target"),
    ("fac.equipment", "id"): stable_id("equipment item"),
    ("fac.equipment", "kind"): d.enum("type of equipment"),
    ("fac.equipment", "laser_codes"): d.list_of("laser codes that the equipment can use"),
    ("fac.equipment", "max_range"): d.quantity("maximum range at which the equipment operates", "Length"),
    ("fac.equipment", "name"): d.name("equipment item", "The name is the identification or the type of the equipment"),
    ("fac.equipment", "notes"): d.text("notes about this equipment, such as limits, supply condition or employment"),
    ("fac.equipment", "quantity"): d.count("items of this equipment that are available"),
    ("fac.equipment", "vertical_accuracy"): d.quantity("vertical precision of the equipment that its data gives", "Length"),
    ("fac", "extensions"): d.extension("The data in this field is for one consumer",
                                       "The controller record keeps the data that all consumers can use",
                                       "Examples are the identification, the equipment and the functions of the controller"),
    ("fac", "id"): stable_id("controller"),
    ("fac", "initial_points"): d.references("initial points", "the controller uses for attack briefs",
                                            "Each one refers to a point with the role initial or fix"),
    ("fac", "kind"): d.discriminator("a forward air controller"),
    ("fac", "laser_codes"): d.list_of("laser codes that the designators of the controller can use"),
    ("fac", "platform"): d.enum("platform of the controller: on the ground (`ground`) or in an aircraft (`airborne`)"),
    ("fac", "position"): d.position("the controller"),
    ("fac", "resources_ref"): EXTERNAL_REF,
    ("fac", "role"): d.enum("qualification of the controller", "The controller is a FAC, a JTAC or a FAC(A)"),
    ("fac", "smoke_color"): d.enum("colour of the smoke that identifies targets or friendly positions"),
    ("fac", "terminal_control"): d.list_of("types of terminal attack control that the controller may give"),

    # ---- Vox Bellica JTAC extension -------------------------------------------------------------
    ("VoxJTACSettings", None): d.entity("JTAC extension of Vox Bellica", "a group of values for the JTAC function of Vox Bellica",
                                        "The names and units are the same as in Vox Bellica",
                                        "Other consumers ignore this extension"),
    ("VoxJTACSettings", "source_unit"): d.statement("This field gives the name of the DCS unit that gives the position of the controller",
                                                    "This unit is also the first observer and the laser source"),
    ("VoxJTACSettings", "group"): d.statement("This field gives the name of a DCS group", "Each unit of the group that operates is an observer"),
    ("VoxJTACSettings", "observers"): d.list_of("names of DCS units or groups", "are more observers and laser sources of the controller"),
    ("VoxJTACSettings", "danger_close"): d.entity("Danger close values", "the values for the workflow of the danger close authority"),
    ("VoxJTACSettings.danger_close", "initials"): d.text("initials of the ground commander for the workflow of the danger close authority in the consumer"),
    ("VoxJTACSettings", "fah"): d.entity("Values of the attack heading", "the values that the controller uses to plan the final attack heading"),
    ("VoxJTACSettings.fah", "friendly_parallel_reds"): d.quantity("limit for friendly lines that are parallel to the heading", None,
                                                                  "units of the risk-estimate distance"),
    ("VoxJTACSettings.fah", "laser_cone"): d.flag("the controller gives priority to attack headings in the laser attack cone"),
    ("VoxJTACSettings.fah", "laser_cone_deg"): d.quantity("angle of the laser attack cone", None, "degrees"),
    ("VoxJTACSettings.fah", "laser_prefer_deg"): d.quantity("primary angle in the laser attack cone", None, "degrees"),
    ("VoxJTACSettings.fah", "observer_buffer_m"): d.quantity("distance that the controller keeps around the observer", None, "metres"),
    ("VoxJTACSettings.fah", "road_max_m"): d.quantity("primary maximum distance to roads", None, "metres"),
    ("VoxJTACSettings.fah", "terrain"): d.flag("the controller uses terrain and roads to plan the heading"),
    ("VoxJTACSettings.fah", "valley_min_depth_m"): d.quantity("primary minimum depth of a valley", None, "metres"),
    ("VoxJTACSettings", "impact_window_s"): d.quantity("period of the observation for the weapon impact", None, "seconds"),
    ("VoxJTACSettings", "laser_range_m"): d.quantity("maximum range at which the observer can lase", None, "metres"),
    ("VoxJTACSettings", "last_call_on_loss"): d.flag("the controller transmits a last call after it has no more observers"),
    ("VoxJTACSettings", "launch_warnings"): d.entity("Launch warning values", "the values for the launch warnings about SAMs"),
    ("VoxJTACSettings.launch_warnings", "coalesce"): d.text("time interval in which the controller sends one report for all launches", GO_DURATION),
    ("VoxJTACSettings.launch_warnings", "delay_max"): d.text("maximum time interval before the controller gives a launch warning", GO_DURATION),
    ("VoxJTACSettings.launch_warnings", "delay_min"): d.text("minimum time interval before the controller gives a launch warning", GO_DURATION),
    ("VoxJTACSettings.launch_warnings", "enabled"): d.flag("the controller sends a report of the SAM launches that it sees"),
    ("VoxJTACSettings.launch_warnings", "range_m"): d.quantity("range of the launch warnings", None, "metres"),
    ("VoxJTACSettings", "memory_file"): d.text("path of the file in which the consumer keeps the pilot memory",
                                               "The file is local to the consumer and is not an interchange dependency"),
    ("VoxJTACSettings", "night"): d.entity("Day and night values", "the values for the day mode and the night mode"),
    ("VoxJTACSettings.night", "end_hour"): d.time("at which the night operation stops, as a local hour"),
    ("VoxJTACSettings.night", "ir_mark"): d.flag("the controller uses an infrared pointer to identify targets at night"),
    ("VoxJTACSettings.night", "mode"): d.enum("operation mode: automatic (`auto`), day (`day`) or night (`night`)"),
    ("VoxJTACSettings.night", "snake_amplitude_m"): d.quantity("amplitude of the movement of the infrared pointer", None, "metres"),
    ("VoxJTACSettings.night", "snake_period"): d.text("period of the movement of the infrared pointer", GO_DURATION),
    ("VoxJTACSettings.night", "start_hour"): d.time("at which the night operation starts, as a local hour"),
    ("VoxJTACSettings.night", "sun_deg"): d.quantity("solar elevation limit for the night operation", None, "degrees"),
    ("VoxJTACSettings.night", "utc_offset_h"): d.quantity("offset of local time from UTC", None, "hours"),
    ("VoxJTACSettings", "precise_coords_delay_s"): d.quantity("time interval before the controller makes the coordinates more accurate",
                                                              None, "seconds",
                                                              "With a negative value, Vox Bellica makes the coordinates more accurate immediately"),
    ("VoxJTACSettings", "readback_timeout_s"): d.quantity("time interval before the controller gives the readback prompt", None, "seconds"),
    ("VoxJTACSettings", "search_range_m"): d.quantity("radius of the search for targets", None, "metres"),
    ("VoxJTACSettings", "stack"): d.entity("Holding stack values", "the values for the holding stack of the aircraft that operate with the controller"),
    ("VoxJTACSettings.stack", "block_ft"): d.quantity("depth of the fixed-wing holding block", None, "feet"),
    ("VoxJTACSettings.stack", "concurrent"): d.flag("the controller lets aircraft do engagements in different target areas at the same time"),
    ("VoxJTACSettings.stack", "fast_floor_ft"): d.quantity("floor of the hold for fast-jets", None, "feet"),
    ("VoxJTACSettings.stack", "helo_block_ft"): d.quantity("depth of the helicopter holding block", None, "feet"),
    ("VoxJTACSettings.stack", "helo_floor_ft"): d.quantity("floor of the hold for helicopters", None, "feet"),
    ("VoxJTACSettings.stack", "radius_m"): d.quantity("radius in which the controller puts targets in one target area", None, "metres"),
    ("VoxJTACSettings.stack", "separation_ft"): d.quantity("vertical distance between the blocks of the holding stack", None, "feet"),
    ("VoxJTACSettings.stack", "slow_floor_ft"): d.quantity("floor of the slow-mover hold", None, "feet"),
    ("VoxJTACSettings", "town_ips"): d.flag("the controller may use town names to make a missing initial point"),
    ("VoxJTACSettings", "voice_id"): d.reference("voice", "this controller uses"),

    # ---- JIPTL ----------------------------------------------------------------------------------
    ("jiptl", None): d.root("Joint integrated prioritized target list", "JIPTL",
                            "a list of the targets of all the force, in the sequence of their priority",
                            "Each entry identifies a target that the planners examine and gives its priority",
                            "An entry may also give the location, the necessary effect, the tasking and the coordination data"),
    ("jiptl", "$schema"): SCHEMA_ID,
    ("jiptl", "extensions"): d.extension(),
    ("jiptl", "meta"): d.statement("This field gives the identification, revision and issue data of this list"),
    ("jiptl", "targets"): d.list_of("targets, in the sequence of their priority", None,
                                    "Each entry identifies a target and gives its priority number", "Number 1 is the highest priority"),
    ("JIPTLTarget", None): d.entity("Target entry", "an entry for one target on a JIPTL, with its identification and priority",
                                    "The optional fields give the location, the necessary effect, the component with the task and the weapon systems"),
    ("JIPTLTarget", "authorized_engagement_means"): d.list_of("weapon systems that have clearance to engage the target", None,
                                                              "Each entry gives the system, and can refer to the SCL and the weapon in the resource catalogue"),
    ("JIPTLTarget", "component_tasked"): d.enum("component of the joint force that has the task to prosecute this target"),
    ("JIPTLTarget", "desired_effect"): d.enum("effect on the target that the commander wants"),
    ("JIPTLTarget", "location"): d.position("the target at the time of approval", "A producer updates the position after a dynamic retasking"),
    ("JIPTLTarget", "location_mgrs"): MGRS,
    ("JIPTLTarget", "priority_rank"): d.statement("This field gives the priority number of the target on the JIPTL", "Number 1 is the highest priority"),
    ("JIPTLTarget", "status"): d.enum("lifecycle condition of the target at this time"),
    ("JIPTLTarget", "target_description"): d.text("data that tells the type of the target and how it is important"),
    ("JIPTLTarget", "target_name"): d.name("target", "The name is short, for example `ENY MRC CP, OBJ HAMMER`"),
    ("JIPTLTarget", "target_number"): d.identifier("target", None,
                                                   "The value is a basic encyclopedia number, such as `BE-0042-01`, or a local number, such as `TGT 0042`"),

    # ---- Report definitions ---------------------------------------------------------------------
    ("ReportDefinition", None): d.entity("Report definition", "a report that a unit should send", "ATP 6-02.x and the SOP of the unit give the report"),
    ("ReportDefinition", "classification"): d.text("highest security classification of the data in the report"),
    ("ReportDefinition", "format_ref"): d.text("reference to the format of the report", "Examples are a paragraph of an SOP and a USMTF format"),
    ("ReportDefinition", "frequency"): d.text("interval at which units send the report, such as `Daily NLT 0600` or `On event`"),
    ("ReportDefinition", "medium"): d.text("transmission method of the report, such as `SIPR email`, `FM voice` or `JBC-P`"),
    ("ReportDefinition", "name"): d.name("report", "Examples are `SITREP`, `LOGSTAT` and `CASREP`"),
    ("ReportDefinition", "precedence"): d.enum("message precedence of the report, as JP 6-0 gives it"),
    ("ReportDefinition", "recipient"): d.text("recipient of the report"),
    ("ReportDefinition", "submitter"): d.text("unit or staff section that has the task to send the report"),
    ("ReportDefinition", "trigger"): d.text("event or schedule that causes a unit to send the report"),

    # ---- TST ------------------------------------------------------------------------------------
    ("tst", None): d.root("Time-sensitive targets", "TST",
                          "targets that it is necessary to engage immediately",
                          "A target is on the list when it is dangerous to friendly forces at this time or in a short time",
                          "A target of opportunity that is very important and available for a short time only is also on the list",
                          "Each entry has the data to find, identify and engage the target in its window"),
    ("tst", "$schema"): SCHEMA_ID,
    ("tst", "extensions"): d.extension(),
    ("tst", "meta"): d.statement("This field gives the identification, revision and issue data of this list"),
    ("tst", "targets"): d.list_of("time-sensitive targets of the mission", None,
                                  "It is necessary to engage each target immediately"),
    ("TSTEntry", None): d.entity("Time-sensitive target entry", "one row on the TST list",
                                 "The joint force commander designates each TST and has its engagement authority",
                                 "The joint force commander may delegate this authority to a component commander or to a lower level",
                                 "Forces prosecute a TST with dynamic targeting: find, fix, track, target, engage and assess"),
    ("TSTEntry", "activity_window"): d.window("the target is possibly there or active"),
    ("TSTEntry", "authorized_engagement_means"): d.list_of("weapon systems that have clearance to prosecute the TST", None, "Each entry gives the system, and can refer to the SCL and the weapon in the resource catalogue"),
    ("opord:TSTEntry", "category"): d.enum("type of the TST by function",
                                           "The type selects the engagement authority in the engagement authority matrix of the order",
                                           "The types are local values and not doctrine"),
    ("frago:TSTEntry", "category"): d.enum("type of the TST by function",
                                           "The type selects the engagement authority in the engagement authority matrix of the order",
                                           "The types are local values and not doctrine"),
    ("TSTEntry", "category"): d.text("type of the target, such as air defence or leadership",
                                     "The types are local values and not a code list of the joint force"),
    ("opord:TSTEntry", "engagement_authority"): d.text("authority that gives approval for the engagement, such as `JFACC`, `JSOTF Cdr` or `BCT Cdr`",
                                                       "The joint force commander has this authority and may delegate it to a component commander or to a lower level"),
    ("frago:TSTEntry", "engagement_authority"): d.text("authority that gives approval for the engagement, such as `JFACC`, `JSOTF Cdr` or `BCT Cdr`",
                                                       "The joint force commander has this authority and may delegate it to a component commander or to a lower level"),
    ("TSTEntry", "engagement_authority"): d.reference("command and control agency", "gives approval for the engagement of this target",
                                                 "The joint force commander has this authority and may delegate it to a component commander or to a lower level"),
    ("TSTEntry", "expected_locations"): d.list_of("positions at which the target can possibly be"),
    ("TSTEntry.expected_locations", "mgrs"): MGRS,
    ("TSTEntry.expected_locations", "name"): d.name("possible location"),
    ("TSTEntry.expected_locations", "position"): d.position("the possible location"),
    ("TSTEntry", "expiration_criteria"): d.text("conditions or time for the removal of the target from the list"),
    ("TSTEntry", "priority"): d.statement("This field gives the priority of this target in relation to the other time-sensitive targets in the list",
                                          "Priority 1 is the highest", "The value is a local priority and not a priority level from the doctrine of the joint force"),
    ("TSTEntry", "roe_constraints"): d.text("ROE limits for this TST", "These limits add to the usual ROE"),
    ("TSTEntry", "target_description"): d.text("data about the type of the target and the signs that units can see"),
    ("TSTEntry", "tst_number"): d.identifier("TST", None, "Examples are `TST-01` and `TST-02`"),

    # ---- Resource catalogue ---------------------------------------------------------------------
    ("resources", None): d.root("Resource catalogue", None,
                                "a catalogue with a version that contains the resources that plans and control measures refer to",
                                "Each resource has a name"),
    ("resources", "$schema"): SCHEMA_ID,
    ("resources", "extensions"): d.extension(),
    ("Aimpoint", "description"): d.text("data about this aimpoint and its local conditions"),
    ("Aimpoint", "elevation"): d.quantity("elevation of the aimpoint above MSL", "Elevation"),
    ("Aimpoint", "name"): d.name("aimpoint"),
    ("Aimpoint", "position"): d.position("the aimpoint"),
    ("Area", "active"): d.window("the area is active", "The value is a schedule, or one continuous period"),
    ("Area", "altitude"): d.altitude_block("the area"),
    ("Area", "geometry"): d.geometry("the area", "a circle, a polygon, a corridor, a rectangle or an ellipse"),
    ("Area", "name"): d.name("area"),
    ("Area", "restrictions"): d.list_of("limits and conditions that are applicable to this area"),
    ("AreaTarget", "description"): d.text("data about this target and the conditions of the operation"),
    ("AreaTarget", "name"): d.name("area target"),
    ("AreaTarget", "restrictions"): d.list_of("limits and conditions on tasks against this target"),
    ("AreaTarget", "source"): SOURCE,
    ("Channel", "frequency"): d.quantity("frequency of the channel", "Frequency", "The value includes the modulation"),
    ("Channel", "name"): d.name("channel"),
    ("Channel", "notes"): d.text("notes about this channel"),
    ("Channel", "usage"): d.text("function of the channel"),
    ("FixedTarget", "description"): d.text("data about this target and the conditions of the operation"),
    ("FixedTarget", "name"): d.name("fixed target"),
    ("FixedTarget", "restrictions"): d.list_of("limits and conditions on tasks against this target"),
    ("FixedTarget", "source"): SOURCE,
    ("LastKnownPosition", "position"): d.position("the last known position"),
    ("MobileTarget", "description"): d.text("data about this target and the conditions of the operation"),
    ("MobileTarget", "name"): d.name("mobile target"),
    ("MobileTarget", "restrictions"): d.list_of("limits and conditions on tasks against this target"),
    ("MobileTarget", "source"): SOURCE,
    ("ResourceData", "agencies"): d.map_of("command and control agencies"),
    ("ResourceData", "areas"): d.map_of("planning areas that are not control measures"),
    ("ResourceData", "channels"): d.map_of("radio channels"),
    ("ResourceData", "control_measures"): d.map_of("control measures"),
    ("ResourceData", "extensions"): d.extension(),
    ("ResourceData", "instrument_procedures"): d.map_of("instrument procedures that airfields refer to"),
    ("ResourceData", "localizers"): d.map_of("localizers to which airfields and the ends of runways refer"),
    ("ResourceData", "pattern_profiles"): d.map_of(
        "traffic pattern profiles that airfields refer to", None,
        d.enforced("A traffic pattern profile in this map shall not refer to a traffic pattern profile", "validator:openaix.check.navigation.pattern_profiles")),
    ("ResourceData", "places"): d.map_of(
        "operating locations for departure, recovery, diversion and transport: airfields, carriers and FARPs"),
    ("ResourceData", "procedures"): d.map_of("procedures"),
    ("ResourceData", "reports"): d.map_of("report definitions that taskings refer to in their report requirements"),
    ("ResourceData", "routes"): d.map_of("routes"),
    ("ResourceData", "scls"): d.map_of("SCLs"),
    ("ResourceData", "aircraft_types"): d.map_of("aircraft types"),
    ("ResourceData", "stores"): d.map_of("weapons, pods, tanks and other stores"),
    ("ResourceData", "targets"): d.map_of("fixed targets, mobile targets and area targets"),
    ("ResourceData", "threats"): d.map_of("possible threats"),
    ("Route", "name"): d.name("route"),
    ("RoutePoint", "altitude"): d.quantity("altitude that the order gives for this route point", "Altitude"),
    ("RoutePoint", "id"): stable_id("route point"),
    ("RoutePoint", "instructions"): d.list_of("instructions for this route point"),
    ("RoutePoint", "name"): d.name("route point"),
    ("RoutePoint", "position"): d.position("the route point"),
    ("Store", "name"): d.name("store"),
    ("Store", "notes"): d.text("notes about this store"),
    ("Store", "family"): d.text("store family, such as `AIM-120` for an `AIM-120C`",
                                "A load variant can use a different store of the same store family"),
    ("Store", "role"): d.enum("function of the pod",
                              d.enforced("Only a store of the `pod` type shall have a role", "schema:then")),
    ("Threat", "description"): d.text("data about this threat and its local conditions"),
    ("Threat", "name"): d.name("threat"),
    ("Threat", "source"): SOURCE,

    # ---- SPINS ----------------------------------------------------------------------------------
}


ENUMS = {
    ("PreplannedAttack", "role"): d.values({
        "strike": "an attack on surface targets in the plan",
        "sead": "an attack that neutralizes or temporarily degrades enemy air defences on the surface, or destroys them",
        "dead": d.value("an attack that destroys enemy air defences on the surface", "After the attack, they cannot engage aircraft again", "This is an openAIX value with no doctrinal source"),
        "scheduled_cas": d.value("preplanned close air support (CAS) at a time on target that the schedule gives",
                                 "JP 3-09.3 (2014) paragraph 27 gives this type of CAS"),
        "maritime_attack": "an attack on maritime surface targets",
        "air_interdiction": d.value("air interdiction, which is an attack on enemy surface forces before they can engage friendly forces",
                                    "The attack occurs at a distance from friendly forces"),
    }),
    ("AttackAssignment", "desired_effect"): d.values({
        value: d.value_sentence(meaning, "This is an openAIX value with no doctrinal source")
        for value, meaning in {"DESTROY": "The attack destroys the target", "NEUTRALIZE": "The attack neutralizes the target",
                               "SUPPRESS": "The attack suppresses the target", "DISRUPT": "The attack disrupts the target",
                               "DEGRADE": "The attack degrades the target",
                               "DENY": "After the attack, the enemy cannot use the target",
                               "DIVERT": "The attack diverts the target or its resources"}.items()}),
    ("aco.assignments", "usage"): d.values({
        "aar": "airspace for AAR, in which tankers give fuel to other aircraft in flight",
        "aew": "airspace for airborne early warning and control aircraft, which find air tracks at long range and control "
               "friendly aircraft",
        "cap": "airspace for a CAP, in which fighters destroy enemy aircraft before they get to their targets",
        "fires": "the coordination of fires from the air or the surface, for example an open kill box or a closed kill box",
        "holding": "the holding or the marshalling of aircraft",
        "isr": "airspace for aircraft that collect intelligence about the enemy and the area by surveillance and reconnaissance",
        "training": "an exercise or a training operation",
        "transit": "a transit through a corridor or along a route",
    }),
    ("CounterAir", "mission_type"): d.values({
        "fighter_sweep": d.value("an offensive counterair mission",
                                 "Fighters go into a specified area to find and destroy enemy aircraft or a target of opportunity"),
        "interception": d.value("an air intercept",
                                "Fighters contact an air track to identify it",
                                "The track is a hostile track, a possibly hostile track or an unknown track",
                                "An air intercept does not authorize an engagement"),
    }),
    ("PersonnelRecovery", "role"): d.values({
        "combat_search_and_rescue": "CSAR, which is the recovery of isolated personnel during combat",
        "search_and_rescue": "SAR, which is aid to persons in distress in a permissive environment",
    }),
    ("Transport", "role"): d.values({
        "aeromedical_evacuation": d.value("the movement of patients by air",
                                          "Medical personnel control the patients and give them treatment en-route"),
        "airlift": "the movement of personnel and materiel by air",
        "humanitarian_assistance": "airlift for a humanitarian assistance operation",
        "noncombatant_evacuation": "airlift for a noncombatant evacuation operation",
        "air_assault": d.value("an air assault", "The aircraft are helicopters or tiltrotor aircraft",
                               "They move assault forces that engage enemy forces or hold terrain"),
        "airdrop": "an airdrop of personnel or materiel from aircraft in flight",
    }),
    ("c2-agency", "role"): d.values({
        "AOC": d.value("the AOC, which plans, controls and assesses air operations",
                       "It publishes the ATO and the ACO"),
        "ASOC": "the ASOC, which controls the air operations that help ground forces directly",
        "ATC": "ATC, which gives air traffic services such as approach control, tower control or range control",
        "AWACS": "the AWACS, which gives airborne surveillance, early warning and control",
        "CRC": "the CRC, which is an element on the ground for surveillance, identification and control of air operations",
        "DASC": "the DASC, which is the Marine Corps agency that controls the air operations that help ground forces directly",
        "JTAC": "a JTAC, who controls CAS aircraft from a forward position",
        "TACP": d.value("a TACP, which is an air liaison element with a ground unit",
                        "It sends air support requests and gives terminal attack control"),
    }),
    ("fac", "coordinate_source"): d.values({
        "exact": "accurate coordinates from the simulator",
        "lrf": "coordinates from a laser rangefinder at a known observer position",
        "visual": "a visual estimate by the controller",
    }),
}
